theme: jekyll-theme-minimal
title: scottkaz.com
description: Hi! I'm Scott Kazmierowicz. Welcome to my personal site, where you'll find some writings, readings, and other fun content. :)
logo: /assets/img/logo.png
